version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: topicos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: topicos
      DB_USER: postgres
      DB_PASS: postgres
      PORT: 8080
    depends_on:
      - db
    ports:
      - "8080:8080"
